server:
  port: 3001

spring:
  application:
    name: codeworld-cloud-cart
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/codeworld-cloud-shop?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        register-enabled: true
        weight: 1
  redis:
    host: 192.168.2.4
    database: 4
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    virtual-host: /codeworld-shop
    host: 192.168.2.2
    username: feicheng
    password: mengli090420
    template:
      exchange: CODEWORLD-SHOP.EXCHANGE #默认交换机CODEWORLD-SHOP.EXCHANGE
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:log/logback-spring.xml
  level:
    com.codeworld.fc.cart.mapper: debug
codeworld:
  jwt:
    secret: codeworld@Login(Auth}*^31)&codeworld% # 用于生存rsa公钥和私钥的密文,越复杂越好
    pubKeyPath: D:\\temp\\rsa\\rsa.pub # 公钥地址
    priKeyPath: D:\\temp\\rsa\\rsa.pri # 私钥地址
    expire: 30   # 过期时间,单位分钟
    cookieMaxAge: 1800
    cookieName: token
